<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FishrApplication;
use Carbon\Carbon;

class FisherfolkRegisteredSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * FishR number format: FISHR-YYYY-NNN (sequential, no -B- distinction).
     * Boat owners are simply the next numbers after the non-boat fisherfolk
     * within the same year. The BoatrRegisteredSeeder references these same numbers.
     *
     * 2024: non-boat = 001–009, boat owners = 010–123
     * 2025: non-boat = 001–038, boat owners = 039–068
     * 2026: non-boat = 001–005, boat owners = 006–012
     */
    public function run(): void
    {
        $this->command->info('Starting FisherfolkRegisteredSeeder...');

        $fisherfolkData = [

            // =========================================================
            // ORIGINAL REGISTERED FISHERFOLK (non-boat)
            // =========================================================

            // ==================== 2024 DATA ====================
            ['first_name'=>'MOHAMMAD MUSA', 'middle_name'=>'ENGKENG',       'last_name'=>'AHMAD',           'sex'=>'Male',   'contact_number'=>'09171234501', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-001','registration_number'=>'FISHR-2024-001','created_at'=>Carbon::create(2024,1,15)],
            ['first_name'=>'GLORIA',         'middle_name'=>'MARQUEZ',       'last_name'=>'APILAN',          'sex'=>'Female', 'contact_number'=>'09181234502', 'barangay'=>'Cuyab',    'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-002','registration_number'=>'FISHR-2024-002','created_at'=>Carbon::create(2024,1,20)],
            ['first_name'=>'MERLINDA',       'middle_name'=>'PADILLA',       'last_name'=>'BORJA',           'sex'=>'Female', 'contact_number'=>'09191234503', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-003','registration_number'=>'FISHR-2024-003','created_at'=>Carbon::create(2024,2,5)],
            ['first_name'=>'LUISITO',        'middle_name'=>'ORPEL',         'last_name'=>'CASILAG',         'sex'=>'Male',   'contact_number'=>'09171234504', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-004','registration_number'=>'FISHR-2024-004','created_at'=>Carbon::create(2024,2,10)],
            ['first_name'=>'APRONIANO',      'middle_name'=>'TRASMIL',       'last_name'=>'FILIPINAS',       'sex'=>'Male',   'contact_number'=>'09181234505', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-005','registration_number'=>'FISHR-2024-005','created_at'=>Carbon::create(2024,3,5)],
            ['first_name'=>'ALFONSO',        'middle_name'=>'ABUNDO',        'last_name'=>'TEMPROZA',        'sex'=>'Male',   'contact_number'=>'09191234506', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-006','registration_number'=>'FISHR-2024-006','created_at'=>Carbon::create(2024,3,12)],
            ['first_name'=>'NURMIN',         'middle_name'=>'ASLIM',         'last_name'=>'TOTOH',           'sex'=>'Male',   'contact_number'=>'09171234507', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-007','registration_number'=>'FISHR-2024-007','created_at'=>Carbon::create(2024,4,8)],
            ['first_name'=>'SOFIA',          'middle_name'=>'AMAGO',         'last_name'=>'TRONO',           'sex'=>'Female', 'contact_number'=>'09181234508', 'barangay'=>'Cuyab',    'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2024-008','registration_number'=>'FISHR-2024-008','created_at'=>Carbon::create(2024,4,15)],
            ['first_name'=>'MELCHOR',        'middle_name'=>'ROBLES',        'last_name'=>'YARIS',           'sex'=>'Male',   'contact_number'=>'09191234509', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture',    'secondary_livelihood'=>'vending','fishr_number'=>'FISHR-2024-009','registration_number'=>'FISHR-2024-009','created_at'=>Carbon::create(2024,5,3)],

            // ==================== 2024 BOAT OWNERS (continuing from 010) ====================
            ['first_name'=>'TEODORO',        'middle_name'=>null,   'last_name'=>'CLEMENTE',        'sex'=>'Male',   'contact_number'=>'09171234510', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-010','registration_number'=>'FISHR-2024-010','created_at'=>Carbon::create(2024,1,14)],
            ['first_name'=>'RONALD',         'middle_name'=>'E.',   'last_name'=>'CURAMPEZ',        'sex'=>'Male',   'contact_number'=>'09181234511', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-011','registration_number'=>'FISHR-2024-011','created_at'=>Carbon::create(2024,1,17)],
            ['first_name'=>'ARTEMIO',        'middle_name'=>'B.',   'last_name'=>'GUAB',            'sex'=>'Male',   'contact_number'=>'09191234512', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-012','registration_number'=>'FISHR-2024-012','created_at'=>Carbon::create(2024,1,23)],
            ['first_name'=>'CHRISTIAN',      'middle_name'=>'P.',   'last_name'=>'MAGO',            'sex'=>'Male',   'contact_number'=>'09171234513', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-013','registration_number'=>'FISHR-2024-013','created_at'=>Carbon::create(2024,2,1)],
            ['first_name'=>'FREDDIE',        'middle_name'=>'H.',   'last_name'=>'JUANERIO',        'sex'=>'Male',   'contact_number'=>'09181234514', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-014','registration_number'=>'FISHR-2024-014','created_at'=>Carbon::create(2024,2,4)],
            ['first_name'=>'DARYL',          'middle_name'=>null,   'last_name'=>'ILAGAN',          'sex'=>'Male',   'contact_number'=>'09191234515', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-015','registration_number'=>'FISHR-2024-015','created_at'=>Carbon::create(2024,2,7)],
            ['first_name'=>'CRISPIN',        'middle_name'=>'A.',   'last_name'=>'VILLADIEGO',      'sex'=>'Male',   'contact_number'=>'09171234516', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-016','registration_number'=>'FISHR-2024-016','created_at'=>Carbon::create(2024,2,10)],
            ['first_name'=>'DEMETRIO',       'middle_name'=>'C.',   'last_name'=>'MORENO',          'sex'=>'Male',   'contact_number'=>'09181234517', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-017','registration_number'=>'FISHR-2024-017','created_at'=>Carbon::create(2024,2,13)],
            ['first_name'=>'RYAN',           'middle_name'=>'B.',   'last_name'=>'ANGELES',         'sex'=>'Male',   'contact_number'=>'09191234518', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-018','registration_number'=>'FISHR-2024-018','created_at'=>Carbon::create(2024,2,16)],
            ['first_name'=>'EDGAR',          'middle_name'=>'A.',   'last_name'=>'ALAMO',           'sex'=>'Male',   'contact_number'=>'09171234519', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-019','registration_number'=>'FISHR-2024-019','created_at'=>Carbon::create(2024,2,19)],
            ['first_name'=>'MARIANO',        'middle_name'=>'M.',   'last_name'=>'MACALINAO',       'sex'=>'Male',   'contact_number'=>'09181234520', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-020','registration_number'=>'FISHR-2024-020','created_at'=>Carbon::create(2024,2,22)],
            ['first_name'=>'RICO',           'middle_name'=>'O.',   'last_name'=>'MACHADO',         'sex'=>'Male',   'contact_number'=>'09191234521', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-021','registration_number'=>'FISHR-2024-021','created_at'=>Carbon::create(2024,2,25)],
            ['first_name'=>'ALFREDO',        'middle_name'=>'T.',   'last_name'=>'CAOYONG',         'sex'=>'Male',   'contact_number'=>'09171234522', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-022','registration_number'=>'FISHR-2024-022','created_at'=>Carbon::create(2024,3,5)],
            ['first_name'=>'LORENZO',        'middle_name'=>'R.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09181234523', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-023','registration_number'=>'FISHR-2024-023','created_at'=>Carbon::create(2024,3,8)],
            ['first_name'=>'RUEL',           'middle_name'=>'M.',   'last_name'=>'GUMAL',           'sex'=>'Male',   'contact_number'=>'09191234524', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-024','registration_number'=>'FISHR-2024-024','created_at'=>Carbon::create(2024,3,11)],
            ['first_name'=>'RODITO',         'middle_name'=>'M.',   'last_name'=>'GUMAL',           'sex'=>'Male',   'contact_number'=>'09171234525', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-025','registration_number'=>'FISHR-2024-025','created_at'=>Carbon::create(2024,3,14)],
            ['first_name'=>'NOLLIE',         'middle_name'=>'Q.',   'last_name'=>'CAOYONG',         'sex'=>'Male',   'contact_number'=>'09181234526', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-026','registration_number'=>'FISHR-2024-026','created_at'=>Carbon::create(2024,3,17)],
            ['first_name'=>'ARIEL',          'middle_name'=>'N.',   'last_name'=>'DELOS REYES',     'sex'=>'Male',   'contact_number'=>'09191234527', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-027','registration_number'=>'FISHR-2024-027','created_at'=>Carbon::create(2024,3,20)],
            ['first_name'=>'MICHAEL',        'middle_name'=>'S.',   'last_name'=>'HEREDIA',         'sex'=>'Male',   'contact_number'=>'09171234528', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-028','registration_number'=>'FISHR-2024-028','created_at'=>Carbon::create(2024,3,23)],
            ['first_name'=>'ENRICO',         'middle_name'=>'S.',   'last_name'=>'DELOS REYES SR.', 'sex'=>'Male',   'contact_number'=>'09181234529', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-029','registration_number'=>'FISHR-2024-029','created_at'=>Carbon::create(2024,3,26)],
            ['first_name'=>'RENATO',         'middle_name'=>'B.',   'last_name'=>'OLIVAREZ',        'sex'=>'Male',   'contact_number'=>'09191234530', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-030','registration_number'=>'FISHR-2024-030','created_at'=>Carbon::create(2024,3,29)],
            ['first_name'=>'RODRIGO',        'middle_name'=>'B.',   'last_name'=>'DOROTEO',         'sex'=>'Male',   'contact_number'=>'09171234531', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-031','registration_number'=>'FISHR-2024-031','created_at'=>Carbon::create(2024,4,1)],
            ['first_name'=>'JERICKSON',      'middle_name'=>'C.',   'last_name'=>'SILVANO',         'sex'=>'Male',   'contact_number'=>'09181234532', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-032','registration_number'=>'FISHR-2024-032','created_at'=>Carbon::create(2024,4,10)],
            ['first_name'=>'CESAR',          'middle_name'=>null,   'last_name'=>'ABUNDO',          'sex'=>'Male',   'contact_number'=>'09191234533', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-033','registration_number'=>'FISHR-2024-033','created_at'=>Carbon::create(2024,4,13)],
            ['first_name'=>'ELISEO',         'middle_name'=>'C.',   'last_name'=>'ESCUDERO',        'sex'=>'Male',   'contact_number'=>'09171234534', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-034','registration_number'=>'FISHR-2024-034','created_at'=>Carbon::create(2024,4,16)],
            ['first_name'=>'MARCIAL',        'middle_name'=>'L.',   'last_name'=>'TORRES',          'sex'=>'Male',   'contact_number'=>'09181234535', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-035','registration_number'=>'FISHR-2024-035','created_at'=>Carbon::create(2024,4,19)],
            ['first_name'=>'PELAGIO',        'middle_name'=>'A.',   'last_name'=>'GARCIA',          'sex'=>'Male',   'contact_number'=>'09191234536', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-036','registration_number'=>'FISHR-2024-036','created_at'=>Carbon::create(2024,4,22)],
            ['first_name'=>'FERDINAND',      'middle_name'=>'P.',   'last_name'=>'GARCIA',          'sex'=>'Male',   'contact_number'=>'09171234537', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-037','registration_number'=>'FISHR-2024-037','created_at'=>Carbon::create(2024,4,25)],
            ['first_name'=>'RICKY',          'middle_name'=>'C.',   'last_name'=>'CURAMPES',        'sex'=>'Male',   'contact_number'=>'09181234538', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-038','registration_number'=>'FISHR-2024-038','created_at'=>Carbon::create(2024,4,28)],
            ['first_name'=>'EDUARDO',        'middle_name'=>'E.',   'last_name'=>'GONZALES',        'sex'=>'Male',   'contact_number'=>'09191234539', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-039','registration_number'=>'FISHR-2024-039','created_at'=>Carbon::create(2024,5,1)],
            ['first_name'=>'BERLIN',         'middle_name'=>'P.',   'last_name'=>'OLIVAREZ',        'sex'=>'Male',   'contact_number'=>'09171234540', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-040','registration_number'=>'FISHR-2024-040','created_at'=>Carbon::create(2024,5,4)],
            ['first_name'=>'MANUEL',         'middle_name'=>'R.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09181234541', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-041','registration_number'=>'FISHR-2024-041','created_at'=>Carbon::create(2024,5,7)],
            ['first_name'=>'CRISPIN',        'middle_name'=>'R.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09191234542', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-042','registration_number'=>'FISHR-2024-042','created_at'=>Carbon::create(2024,5,10)],
            ['first_name'=>'LARIO',          'middle_name'=>'J.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09171234543', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-043','registration_number'=>'FISHR-2024-043','created_at'=>Carbon::create(2024,5,13)],
            ['first_name'=>'ROBERT',         'middle_name'=>'T.',   'last_name'=>'CORDOVA',         'sex'=>'Male',   'contact_number'=>'09181234544', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-044','registration_number'=>'FISHR-2024-044','created_at'=>Carbon::create(2024,5,16)],
            ['first_name'=>'FLORENTINO',     'middle_name'=>'R.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09191234545', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-045','registration_number'=>'FISHR-2024-045','created_at'=>Carbon::create(2024,5,19)],
            ['first_name'=>'ROGER',          'middle_name'=>'A.',   'last_name'=>'TEÑIDO',          'sex'=>'Male',   'contact_number'=>'09171234546', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-046','registration_number'=>'FISHR-2024-046','created_at'=>Carbon::create(2024,5,22)],
            ['first_name'=>'VENANCIO',       'middle_name'=>'C.',   'last_name'=>'SARIO',           'sex'=>'Male',   'contact_number'=>'09181234547', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-047','registration_number'=>'FISHR-2024-047','created_at'=>Carbon::create(2024,5,25)],
            ['first_name'=>'FERNAND',        'middle_name'=>'C.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09191234548', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-048','registration_number'=>'FISHR-2024-048','created_at'=>Carbon::create(2024,5,28)],
            ['first_name'=>'FERNANDO',       'middle_name'=>'R.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09171234549', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-049','registration_number'=>'FISHR-2024-049','created_at'=>Carbon::create(2024,5,31)],
            ['first_name'=>'DANILO',         'middle_name'=>'V.',   'last_name'=>'MACHADO',         'sex'=>'Male',   'contact_number'=>'09181234550', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-050','registration_number'=>'FISHR-2024-050','created_at'=>Carbon::create(2024,6,3)],
            ['first_name'=>'DOMINGO',        'middle_name'=>'Q.',   'last_name'=>'RONCALES',        'sex'=>'Male',   'contact_number'=>'09191234551', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-051','registration_number'=>'FISHR-2024-051','created_at'=>Carbon::create(2024,6,6)],
            ['first_name'=>'GERMAN',         'middle_name'=>'M.',   'last_name'=>'HALAYAHAY',       'sex'=>'Male',   'contact_number'=>'09171234552', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-052','registration_number'=>'FISHR-2024-052','created_at'=>Carbon::create(2024,6,9)],
            ['first_name'=>'ROMAR',          'middle_name'=>'S.',   'last_name'=>'AMION',           'sex'=>'Male',   'contact_number'=>'09181234553', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-053','registration_number'=>'FISHR-2024-053','created_at'=>Carbon::create(2024,6,12)],
            ['first_name'=>'JAIMEE',         'middle_name'=>'V.',   'last_name'=>'MACHADO',         'sex'=>'Male',   'contact_number'=>'09191234554', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-054','registration_number'=>'FISHR-2024-054','created_at'=>Carbon::create(2024,6,15)],
            ['first_name'=>'ROMEO',          'middle_name'=>'R.',   'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09171234555', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-055','registration_number'=>'FISHR-2024-055','created_at'=>Carbon::create(2024,6,18)],
            ['first_name'=>'JIMSON',         'middle_name'=>'M.',   'last_name'=>'BACHECHA',        'sex'=>'Male',   'contact_number'=>'09181234556', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-056','registration_number'=>'FISHR-2024-056','created_at'=>Carbon::create(2024,6,21)],
            ['first_name'=>'JULIUS',         'middle_name'=>'P.',   'last_name'=>'ODERO',           'sex'=>'Male',   'contact_number'=>'09191234557', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-057','registration_number'=>'FISHR-2024-057','created_at'=>Carbon::create(2024,6,24)],
            ['first_name'=>'RICARDO',        'middle_name'=>'R.',   'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09171234558', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-058','registration_number'=>'FISHR-2024-058','created_at'=>Carbon::create(2024,6,27)],
            ['first_name'=>'JAVIER',         'middle_name'=>'M.',   'last_name'=>'BUCALAN',         'sex'=>'Male',   'contact_number'=>'09181234559', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-059','registration_number'=>'FISHR-2024-059','created_at'=>Carbon::create(2024,6,30)],
            ['first_name'=>'ROBERTO',        'middle_name'=>'S.',   'last_name'=>'TEMPROSA',        'sex'=>'Male',   'contact_number'=>'09191234560', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-060','registration_number'=>'FISHR-2024-060','created_at'=>Carbon::create(2024,7,3)],
            ['first_name'=>'AERON BRIAN',    'middle_name'=>'S.',   'last_name'=>'INSORIO',         'sex'=>'Male',   'contact_number'=>'09171234561', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-061','registration_number'=>'FISHR-2024-061','created_at'=>Carbon::create(2024,7,6)],
            ['first_name'=>'DONATO',         'middle_name'=>'N.',   'last_name'=>'MARISTANEZ',      'sex'=>'Male',   'contact_number'=>'09181234562', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-062','registration_number'=>'FISHR-2024-062','created_at'=>Carbon::create(2024,7,9)],
            ['first_name'=>'GRACIANO',       'middle_name'=>'R.',   'last_name'=>'INSORIO',         'sex'=>'Male',   'contact_number'=>'09191234563', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-063','registration_number'=>'FISHR-2024-063','created_at'=>Carbon::create(2024,7,12)],
            ['first_name'=>'AQUILINO',       'middle_name'=>'L.',   'last_name'=>'YAMBAO',          'sex'=>'Male',   'contact_number'=>'09171234564', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-064','registration_number'=>'FISHR-2024-064','created_at'=>Carbon::create(2024,7,15)],
            ['first_name'=>'SENANDO',        'middle_name'=>'A.',   'last_name'=>'BACHECHA JR',     'sex'=>'Male',   'contact_number'=>'09181234565', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-065','registration_number'=>'FISHR-2024-065','created_at'=>Carbon::create(2024,7,18)],
            ['first_name'=>'EDEJIE',         'middle_name'=>'D.',   'last_name'=>'CABANLIT',        'sex'=>'Male',   'contact_number'=>'09191234566', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-066','registration_number'=>'FISHR-2024-066','created_at'=>Carbon::create(2024,7,21)],
            ['first_name'=>'CRISPIN',        'middle_name'=>'A.',   'last_name'=>'TEMPROSA',        'sex'=>'Male',   'contact_number'=>'09171234567', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-067','registration_number'=>'FISHR-2024-067','created_at'=>Carbon::create(2024,7,24)],
            ['first_name'=>'ELBERTO',        'middle_name'=>'E.',   'last_name'=>'CURAMPES',        'sex'=>'Male',   'contact_number'=>'09181234568', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-068','registration_number'=>'FISHR-2024-068','created_at'=>Carbon::create(2024,7,27)],
            ['first_name'=>'MAR',            'middle_name'=>'A.',   'last_name'=>'LIMOSA',          'sex'=>'Male',   'contact_number'=>'09191234569', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-069','registration_number'=>'FISHR-2024-069','created_at'=>Carbon::create(2024,7,30)],
            ['first_name'=>'AGNES',          'middle_name'=>'S.',   'last_name'=>'LIMOSA',          'sex'=>'Female', 'contact_number'=>'09171234570', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-070','registration_number'=>'FISHR-2024-070','created_at'=>Carbon::create(2024,8,2)],
            ['first_name'=>'JAYMEE',         'middle_name'=>'M.',   'last_name'=>'LAZARO',          'sex'=>'Male',   'contact_number'=>'09181234571', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-071','registration_number'=>'FISHR-2024-071','created_at'=>Carbon::create(2024,8,8)],
            ['first_name'=>'ROBERTO',        'middle_name'=>'B.',   'last_name'=>'RAGUIT',          'sex'=>'Male',   'contact_number'=>'09191234572', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-072','registration_number'=>'FISHR-2024-072','created_at'=>Carbon::create(2024,8,11)],
            ['first_name'=>'JASPER',         'middle_name'=>'I.',   'last_name'=>'SARIO',           'sex'=>'Male',   'contact_number'=>'09171234573', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-073','registration_number'=>'FISHR-2024-073','created_at'=>Carbon::create(2024,8,17)],
            ['first_name'=>'MOHAMMAD MUSA',  'middle_name'=>'E.',   'last_name'=>'AHMAD',           'sex'=>'Male',   'contact_number'=>'09181234574', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-074','registration_number'=>'FISHR-2024-074','created_at'=>Carbon::create(2024,8,20)],
            ['first_name'=>'RONALD',         'middle_name'=>'A.',   'last_name'=>'LIM',             'sex'=>'Male',   'contact_number'=>'09191234575', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-075','registration_number'=>'FISHR-2024-075','created_at'=>Carbon::create(2024,8,29)],
            ['first_name'=>'JENNER',         'middle_name'=>'E.',   'last_name'=>'AMAGO',           'sex'=>'Male',   'contact_number'=>'09171234576', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-076','registration_number'=>'FISHR-2024-076','created_at'=>Carbon::create(2024,9,1)],
            ['first_name'=>'JOSE',           'middle_name'=>'A.',   'last_name'=>'TEMPROSA',        'sex'=>'Male',   'contact_number'=>'09181234577', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-077','registration_number'=>'FISHR-2024-077','created_at'=>Carbon::create(2024,9,4)],
            ['first_name'=>'ALBIN',          'middle_name'=>'A.',   'last_name'=>'ALVIAR',          'sex'=>'Male',   'contact_number'=>'09191234578', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-078','registration_number'=>'FISHR-2024-078','created_at'=>Carbon::create(2024,9,7)],
            ['first_name'=>'FERDINAND',      'middle_name'=>'D.',   'last_name'=>'GUILLERMO',       'sex'=>'Male',   'contact_number'=>'09171234579', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-079','registration_number'=>'FISHR-2024-079','created_at'=>Carbon::create(2024,9,10)],
            ['first_name'=>'DARWIN',         'middle_name'=>'B.',   'last_name'=>'CASINOS',         'sex'=>'Male',   'contact_number'=>'09181234580', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-080','registration_number'=>'FISHR-2024-080','created_at'=>Carbon::create(2024,9,13)],
            ['first_name'=>'RANILLO',        'middle_name'=>'N.',   'last_name'=>'SANTAÑEZ',        'sex'=>'Male',   'contact_number'=>'09191234581', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-081','registration_number'=>'FISHR-2024-081','created_at'=>Carbon::create(2024,9,25)],
            ['first_name'=>'ARTEMIO',        'middle_name'=>'V.',   'last_name'=>'ORTEGA',          'sex'=>'Male',   'contact_number'=>'09171234582', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-082','registration_number'=>'FISHR-2024-082','created_at'=>Carbon::create(2024,9,28)],
            ['first_name'=>'MELCHOR',        'middle_name'=>'R.',   'last_name'=>'YARIS',           'sex'=>'Male',   'contact_number'=>'09181234583', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-083','registration_number'=>'FISHR-2024-083','created_at'=>Carbon::create(2024,10,1)],
            ['first_name'=>'GENARO',         'middle_name'=>'G.',   'last_name'=>'DE BORJA',        'sex'=>'Male',   'contact_number'=>'09191234584', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-084','registration_number'=>'FISHR-2024-084','created_at'=>Carbon::create(2024,10,4)],
            ['first_name'=>'JONATHAN',       'middle_name'=>'S.',   'last_name'=>'ESPARAGOZA',      'sex'=>'Male',   'contact_number'=>'09171234585', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-085','registration_number'=>'FISHR-2024-085','created_at'=>Carbon::create(2024,10,7)],

            // ---------- 2024 NON-MOTORIZED boat owners (continuing from 086) ----------
            ['first_name'=>'JERRY',          'middle_name'=>'P.',   'last_name'=>'URIARTE',         'sex'=>'Male',   'contact_number'=>'09181234586', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-086','registration_number'=>'FISHR-2024-086','created_at'=>Carbon::create(2024,1,15)],
            ['first_name'=>'ARIEL',          'middle_name'=>'S.',   'last_name'=>'DELOS REYES SR.', 'sex'=>'Male',   'contact_number'=>'09191234587', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-087','registration_number'=>'FISHR-2024-087','created_at'=>Carbon::create(2024,1,17)],
            ['first_name'=>'DANILO',         'middle_name'=>'F.',   'last_name'=>'HILARIO',         'sex'=>'Male',   'contact_number'=>'09171234588', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-088','registration_number'=>'FISHR-2024-088','created_at'=>Carbon::create(2024,1,19)],
            ['first_name'=>'RONALDO',        'middle_name'=>'E.',   'last_name'=>'AJEDO',           'sex'=>'Male',   'contact_number'=>'09181234589', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-089','registration_number'=>'FISHR-2024-089','created_at'=>Carbon::create(2024,1,21)],
            ['first_name'=>'SILVERIO',       'middle_name'=>'P.',   'last_name'=>'FLAMIANO',        'sex'=>'Male',   'contact_number'=>'09191234590', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-090','registration_number'=>'FISHR-2024-090','created_at'=>Carbon::create(2024,1,23)],
            ['first_name'=>'RONALDO',        'middle_name'=>'M.',   'last_name'=>'LOS BAÑOS',       'sex'=>'Male',   'contact_number'=>'09171234591', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-091','registration_number'=>'FISHR-2024-091','created_at'=>Carbon::create(2024,1,25)],
            ['first_name'=>'MARCOS',         'middle_name'=>'B.',   'last_name'=>'CORDIS',          'sex'=>'Male',   'contact_number'=>'09181234592', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-092','registration_number'=>'FISHR-2024-092','created_at'=>Carbon::create(2024,1,27)],
            ['first_name'=>'ARMANDO',        'middle_name'=>'G.',   'last_name'=>'BAUSO',           'sex'=>'Male',   'contact_number'=>'09191234593', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-093','registration_number'=>'FISHR-2024-093','created_at'=>Carbon::create(2024,1,29)],
            ['first_name'=>'ALEJANDRO',      'middle_name'=>'G.',   'last_name'=>'BAUSO',           'sex'=>'Male',   'contact_number'=>'09171234594', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-094','registration_number'=>'FISHR-2024-094','created_at'=>Carbon::create(2024,1,31)],
            ['first_name'=>'ENRICO',         'middle_name'=>'G.',   'last_name'=>'DELOS REYES JR.', 'sex'=>'Male',   'contact_number'=>'09181234595', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-095','registration_number'=>'FISHR-2024-095','created_at'=>Carbon::create(2024,2,2)],
            ['first_name'=>'VIRGILIO',       'middle_name'=>'S.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09191234596', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-096','registration_number'=>'FISHR-2024-096','created_at'=>Carbon::create(2024,2,4)],
            ['first_name'=>'JAY-AR',         'middle_name'=>'V.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09171234597', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-097','registration_number'=>'FISHR-2024-097','created_at'=>Carbon::create(2024,2,6)],
            ['first_name'=>'ALEXANDER',      'middle_name'=>'B.',   'last_name'=>'CARAN',           'sex'=>'Male',   'contact_number'=>'09181234598', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-098','registration_number'=>'FISHR-2024-098','created_at'=>Carbon::create(2024,2,8)],
            ['first_name'=>'ROBERTO',        'middle_name'=>'R.',   'last_name'=>'ALON-ALON',       'sex'=>'Male',   'contact_number'=>'09191234599', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-099','registration_number'=>'FISHR-2024-099','created_at'=>Carbon::create(2024,2,10)],
            ['first_name'=>'BRIAN',          'middle_name'=>'P.',   'last_name'=>'NAZARENO',        'sex'=>'Male',   'contact_number'=>'09171234600', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-100','registration_number'=>'FISHR-2024-100','created_at'=>Carbon::create(2024,2,12)],
            ['first_name'=>'LAURO',          'middle_name'=>'O.',   'last_name'=>'VIERNEZA',        'sex'=>'Male',   'contact_number'=>'09181234601', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-101','registration_number'=>'FISHR-2024-101','created_at'=>Carbon::create(2024,2,14)],
            ['first_name'=>'EFREN',          'middle_name'=>'M.',   'last_name'=>'VERGARA',         'sex'=>'Male',   'contact_number'=>'09191234602', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-102','registration_number'=>'FISHR-2024-102','created_at'=>Carbon::create(2024,2,16)],
            ['first_name'=>'NICANOR',        'middle_name'=>'A.',   'last_name'=>'BERON',           'sex'=>'Male',   'contact_number'=>'09171234603', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-103','registration_number'=>'FISHR-2024-103','created_at'=>Carbon::create(2024,2,18)],
            ['first_name'=>'EDGAR',          'middle_name'=>'M.',   'last_name'=>'NAVALES',         'sex'=>'Male',   'contact_number'=>'09181234604', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-104','registration_number'=>'FISHR-2024-104','created_at'=>Carbon::create(2024,2,20)],
            ['first_name'=>'BENJAMIN',       'middle_name'=>'S.',   'last_name'=>'BRICENIO',        'sex'=>'Male',   'contact_number'=>'09191234605', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-105','registration_number'=>'FISHR-2024-105','created_at'=>Carbon::create(2024,2,24)],
            ['first_name'=>'EMMANUEL',       'middle_name'=>'P.',   'last_name'=>'CORPUZ',          'sex'=>'Male',   'contact_number'=>'09171234606', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-106','registration_number'=>'FISHR-2024-106','created_at'=>Carbon::create(2024,2,26)],
            ['first_name'=>'GERARDO',        'middle_name'=>'A.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09181234607', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-107','registration_number'=>'FISHR-2024-107','created_at'=>Carbon::create(2024,2,28)],
            ['first_name'=>'ROMEO',          'middle_name'=>'B.',   'last_name'=>'ALMEIDA',         'sex'=>'Male',   'contact_number'=>'09191234608', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-108','registration_number'=>'FISHR-2024-108','created_at'=>Carbon::create(2024,3,1)],
            ['first_name'=>'ONOPRE',         'middle_name'=>'V.',   'last_name'=>'DELA CRUZ',       'sex'=>'Male',   'contact_number'=>'09171234609', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-109','registration_number'=>'FISHR-2024-109','created_at'=>Carbon::create(2024,3,3)],
            ['first_name'=>'VIRGILIO',       'middle_name'=>'V.',   'last_name'=>'CASULLA',         'sex'=>'Male',   'contact_number'=>'09181234610', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-110','registration_number'=>'FISHR-2024-110','created_at'=>Carbon::create(2024,3,7)],
            ['first_name'=>'ALMARIO',        'middle_name'=>'C.',   'last_name'=>'PERBER',          'sex'=>'Male',   'contact_number'=>'09191234611', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-111','registration_number'=>'FISHR-2024-111','created_at'=>Carbon::create(2024,3,9)],
            ['first_name'=>'CARLITO',        'middle_name'=>'O.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09171234612', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-112','registration_number'=>'FISHR-2024-112','created_at'=>Carbon::create(2024,3,11)],
            ['first_name'=>'ROGELIO',        'middle_name'=>'R.',   'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09181234613', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-113','registration_number'=>'FISHR-2024-113','created_at'=>Carbon::create(2024,3,13)],
            ['first_name'=>'MARVIC',         'middle_name'=>'B.',   'last_name'=>'MEJIAS',          'sex'=>'Male',   'contact_number'=>'09191234614', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-114','registration_number'=>'FISHR-2024-114','created_at'=>Carbon::create(2024,3,15)],
            ['first_name'=>'VENANCIO',       'middle_name'=>'O.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09171234615', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-115','registration_number'=>'FISHR-2024-115','created_at'=>Carbon::create(2024,3,19)],
            ['first_name'=>'LARRY',          'middle_name'=>'C.',   'last_name'=>'MARQUEZ',         'sex'=>'Male',   'contact_number'=>'09181234616', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-116','registration_number'=>'FISHR-2024-116','created_at'=>Carbon::create(2024,3,21)],
            ['first_name'=>'ROMANO',         'middle_name'=>'B.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09191234617', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-117','registration_number'=>'FISHR-2024-117','created_at'=>Carbon::create(2024,3,23)],
            ['first_name'=>'JAIME',          'middle_name'=>'R.',   'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09171234618', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-118','registration_number'=>'FISHR-2024-118','created_at'=>Carbon::create(2024,3,25)],
            ['first_name'=>'RICO',           'middle_name'=>'L.',   'last_name'=>'PASCASIO',        'sex'=>'Male',   'contact_number'=>'09181234619', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-119','registration_number'=>'FISHR-2024-119','created_at'=>Carbon::create(2024,3,27)],
            ['first_name'=>'VLADIMIR',       'middle_name'=>'M.',   'last_name'=>'ALAIZA',          'sex'=>'Male',   'contact_number'=>'09191234620', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-120','registration_number'=>'FISHR-2024-120','created_at'=>Carbon::create(2024,3,31)],
            ['first_name'=>'ALMARIO',        'middle_name'=>'V.',   'last_name'=>'VIDAL JR',        'sex'=>'Male',   'contact_number'=>'09171234621', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-121','registration_number'=>'FISHR-2024-121','created_at'=>Carbon::create(2024,4,2)],
            ['first_name'=>'ROMEO',          'middle_name'=>'A.',   'last_name'=>'VIERNEZA JR',     'sex'=>'Male',   'contact_number'=>'09181234622', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-122','registration_number'=>'FISHR-2024-122','created_at'=>Carbon::create(2024,4,4)],
            ['first_name'=>'ALBERTO',        'middle_name'=>'G.',   'last_name'=>'IZON',            'sex'=>'Male',   'contact_number'=>'09191234623', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2024-123','registration_number'=>'FISHR-2024-123','created_at'=>Carbon::create(2024,4,6)],

            // ==================== 2025 DATA ====================
            ['first_name'=>'SUSAN',          'middle_name'=>'LEYVA',         'last_name'=>'AGUILAR',         'sex'=>'Female', 'contact_number'=>'09171235001', 'barangay'=>'Cuyab',    'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-001','registration_number'=>'FISHR-2025-001','created_at'=>Carbon::create(2025,1,10)],
            ['first_name'=>'JEROME',         'middle_name'=>'FRANCISCO',     'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09181235002', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-002','registration_number'=>'FISHR-2025-002','created_at'=>Carbon::create(2025,1,15)],
            ['first_name'=>'MARICAR',        'middle_name'=>'GUTIERES',      'last_name'=>'ANDRADA',         'sex'=>'Female', 'contact_number'=>'09191235003', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-003','registration_number'=>'FISHR-2025-003','created_at'=>Carbon::create(2025,1,20)],
            ['first_name'=>'MICHELLE',       'middle_name'=>'GONZALO',       'last_name'=>'ANDRADA',         'sex'=>'Female', 'contact_number'=>'09171235004', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-004','registration_number'=>'FISHR-2025-004','created_at'=>Carbon::create(2025,2,5)],
            ['first_name'=>'RENANTE',        'middle_name'=>'BALAGOT',       'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09181235005', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-005','registration_number'=>'FISHR-2025-005','created_at'=>Carbon::create(2025,2,8)],
            ['first_name'=>'WILLIE',         'middle_name'=>'REYES',         'last_name'=>'ANDRADA',         'sex'=>'Male',   'contact_number'=>'09191235006', 'barangay'=>'Landayan', 'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-006','registration_number'=>'FISHR-2025-006','created_at'=>Carbon::create(2025,2,12)],
            ['first_name'=>'ALDAM',          'middle_name'=>'ALPHA',         'last_name'=>'ARQUIZA',         'sex'=>'Male',   'contact_number'=>'09171235007', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-007','registration_number'=>'FISHR-2025-007','created_at'=>Carbon::create(2025,3,3)],
            ['first_name'=>'ALMA',           'middle_name'=>'TAJA',          'last_name'=>'AVELINA',         'sex'=>'Female', 'contact_number'=>'09181235008', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-008','registration_number'=>'FISHR-2025-008','created_at'=>Carbon::create(2025,3,10)],
            ['first_name'=>'ROMMEL',         'middle_name'=>'AQUINO',        'last_name'=>'BLANCA',          'sex'=>'Male',   'contact_number'=>'09191235009', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-009','registration_number'=>'FISHR-2025-009','created_at'=>Carbon::create(2025,3,18)],
            ['first_name'=>'FRANCISCO',      'middle_name'=>'LUMANTAS',      'last_name'=>'CANILLIAS',       'sex'=>'Male',   'contact_number'=>'09171235010', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-010','registration_number'=>'FISHR-2025-010','created_at'=>Carbon::create(2025,4,2)],
            ['first_name'=>'JOJIE',          'middle_name'=>'PRODISIMO',     'last_name'=>'CATALON',         'sex'=>'Male',   'contact_number'=>'09181235011', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-011','registration_number'=>'FISHR-2025-011','created_at'=>Carbon::create(2025,4,12)],
            ['first_name'=>'SADJID',         'middle_name'=>'BRILLANTES',    'last_name'=>'CASALIN',         'sex'=>'Male',   'contact_number'=>'09191235012', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-012','registration_number'=>'FISHR-2025-012','created_at'=>Carbon::create(2025,4,22)],
            ['first_name'=>'ARNOLD',         'middle_name'=>'PEREZ',         'last_name'=>'DELA CRUZ',       'sex'=>'Male',   'contact_number'=>'09171235013', 'barangay'=>'Landayan', 'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-013','registration_number'=>'FISHR-2025-013','created_at'=>Carbon::create(2025,5,5)],
            ['first_name'=>'RONILO',         'middle_name'=>'TURING',        'last_name'=>'DESTOPA',         'sex'=>'Male',   'contact_number'=>'09181235014', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-014','registration_number'=>'FISHR-2025-014','created_at'=>Carbon::create(2025,5,15)],
            ['first_name'=>'JOHN NORMAN',    'middle_name'=>'SANTOS',        'last_name'=>'DITABLAN',        'sex'=>'Male',   'contact_number'=>'09191235015', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-015','registration_number'=>'FISHR-2025-015','created_at'=>Carbon::create(2025,5,25)],
            ['first_name'=>'JOEL',           'middle_name'=>'LEDIO',         'last_name'=>'DOMENGUIS',       'sex'=>'Male',   'contact_number'=>'09171235016', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-016','registration_number'=>'FISHR-2025-016','created_at'=>Carbon::create(2025,6,3)],
            ['first_name'=>'RHONA',          'middle_name'=>'RUTAQUIO',      'last_name'=>'DORADO',          'sex'=>'Female', 'contact_number'=>'09181235017', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-017','registration_number'=>'FISHR-2025-017','created_at'=>Carbon::create(2025,6,10)],
            ['first_name'=>'ALBERTO',        'middle_name'=>'VILLAMOR',      'last_name'=>'FRANCISCO',       'sex'=>'Male',   'contact_number'=>'09191235018', 'barangay'=>'Landayan', 'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-018','registration_number'=>'FISHR-2025-018','created_at'=>Carbon::create(2025,6,18)],
            ['first_name'=>'ERICKA MAE',     'middle_name'=>'JOCSON',        'last_name'=>'FUENTES',         'sex'=>'Female', 'contact_number'=>'09171235019', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-019','registration_number'=>'FISHR-2025-019','created_at'=>Carbon::create(2025,7,2)],
            ['first_name'=>'JAY',            'middle_name'=>'MARCHADO',      'last_name'=>'FUENTES',         'sex'=>'Male',   'contact_number'=>'09181235020', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-020','registration_number'=>'FISHR-2025-020','created_at'=>Carbon::create(2025,7,12)],
            ['first_name'=>'DAISYLYN',       'middle_name'=>'DEO',           'last_name'=>'GRANADO',         'sex'=>'Female', 'contact_number'=>'09191235021', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-021','registration_number'=>'FISHR-2025-021','created_at'=>Carbon::create(2025,7,22)],
            ['first_name'=>'MARILYN',        'middle_name'=>'LOZADA',        'last_name'=>'GONZALES',        'sex'=>'Female', 'contact_number'=>'09171235022', 'barangay'=>'Cuyab',    'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-022','registration_number'=>'FISHR-2025-022','created_at'=>Carbon::create(2025,8,5)],
            ['first_name'=>'PAULINO',        'middle_name'=>'OMBIYANG',      'last_name'=>'GUMIAL',          'sex'=>'Male',   'contact_number'=>'09181235023', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-023','registration_number'=>'FISHR-2025-023','created_at'=>Carbon::create(2025,8,15)],
            ['first_name'=>'ASMIL',          'middle_name'=>'TOTOH',         'last_name'=>'HASAN',           'sex'=>'Male',   'contact_number'=>'09191235024', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-024','registration_number'=>'FISHR-2025-024','created_at'=>Carbon::create(2025,8,25)],
            ['first_name'=>'RASID',          'middle_name'=>'USMAN',         'last_name'=>'JACARIA',         'sex'=>'Male',   'contact_number'=>'09171235025', 'barangay'=>'Landayan', 'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-025','registration_number'=>'FISHR-2025-025','created_at'=>Carbon::create(2025,9,3)],
            ['first_name'=>'ALBERT',         'middle_name'=>'DAVID',         'last_name'=>'MANALO',          'sex'=>'Male',   'contact_number'=>'09181235026', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-026','registration_number'=>'FISHR-2025-026','created_at'=>Carbon::create(2025,9,12)],
            ['first_name'=>'REBECCA',        'middle_name'=>'AMIL',          'last_name'=>'MARMETO',         'sex'=>'Female', 'contact_number'=>'09191235027', 'barangay'=>'Cuyab',    'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-027','registration_number'=>'FISHR-2025-027','created_at'=>Carbon::create(2025,9,22)],
            ['first_name'=>'LUZVIMINDA',     'middle_name'=>'RAMOS',         'last_name'=>'MORALES',         'sex'=>'Female', 'contact_number'=>'09171235028', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-028','registration_number'=>'FISHR-2025-028','created_at'=>Carbon::create(2025,10,5)],
            ['first_name'=>'ISAIAS',         'middle_name'=>'BAUSO',         'last_name'=>'NUEZ',            'sex'=>'Male',   'contact_number'=>'09181235029', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>'vending','fishr_number'=>'FISHR-2025-029','registration_number'=>'FISHR-2025-029','created_at'=>Carbon::create(2025,10,15)],
            ['first_name'=>'JHON JOSEPH',    'middle_name'=>'BAUSO',         'last_name'=>'NUEZ',            'sex'=>'Male',   'contact_number'=>'09191235030', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>'vending','fishr_number'=>'FISHR-2025-030','registration_number'=>'FISHR-2025-030','created_at'=>Carbon::create(2025,10,25)],
            ['first_name'=>'ARLYN',          'middle_name'=>'LUCAS',         'last_name'=>'ORTEGA',          'sex'=>'Female', 'contact_number'=>'09171235031', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-031','registration_number'=>'FISHR-2025-031','created_at'=>Carbon::create(2025,11,3)],
            ['first_name'=>'RICHARD',        'middle_name'=>'LASCANO',       'last_name'=>'PASCASIO',        'sex'=>'Male',   'contact_number'=>'09181235032', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-032','registration_number'=>'FISHR-2025-032','created_at'=>Carbon::create(2025,11,12)],
            ['first_name'=>'MARGARITO',      'middle_name'=>'GERONG',        'last_name'=>'ROA',             'sex'=>'Male',   'contact_number'=>'09191235033', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-033','registration_number'=>'FISHR-2025-033','created_at'=>Carbon::create(2025,11,22)],
            ['first_name'=>'RODEL',          'middle_name'=>'MARTINEZ',      'last_name'=>'SADIAN',          'sex'=>'Male',   'contact_number'=>'09171235034', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-034','registration_number'=>'FISHR-2025-034','created_at'=>Carbon::create(2025,12,2)],
            ['first_name'=>'MOHAMMAD',       'middle_name'=>'PAWADJI',       'last_name'=>'SAHI',            'sex'=>'Male',   'contact_number'=>'09181235035', 'barangay'=>'Cuyab',    'main_livelihood'=>'aquaculture','secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-035','registration_number'=>'FISHR-2025-035','created_at'=>Carbon::create(2025,12,8)],
            ['first_name'=>'HECTOR',         'middle_name'=>'LAURIO',        'last_name'=>'SAUQUILLO',       'sex'=>'Male',   'contact_number'=>'09191235036', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-036','registration_number'=>'FISHR-2025-036','created_at'=>Carbon::create(2025,12,15)],
            ['first_name'=>'ANTHONY',        'middle_name'=>'BAUSO',         'last_name'=>'TOMAGAN',         'sex'=>'Male',   'contact_number'=>'09171235037', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-037','registration_number'=>'FISHR-2025-037','created_at'=>Carbon::create(2025,12,20)],
            ['first_name'=>'JOANNE',         'middle_name'=>'LABINE',        'last_name'=>'VIBAR',           'sex'=>'Female', 'contact_number'=>'09181235038', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2025-038','registration_number'=>'FISHR-2025-038','created_at'=>Carbon::create(2025,12,28)],

            // ==================== 2025 BOAT OWNERS (continuing from 039) ====================
            ['first_name'=>'MARIO',          'middle_name'=>'V.',   'last_name'=>'AVELINA JR',      'sex'=>'Male',   'contact_number'=>'09191235039', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-039','registration_number'=>'FISHR-2025-039','created_at'=>Carbon::create(2025,1,13)],
            ['first_name'=>'MARIO',          'middle_name'=>'O.',   'last_name'=>'AVELINA SR',      'sex'=>'Male',   'contact_number'=>'09171235040', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-040','registration_number'=>'FISHR-2025-040','created_at'=>Carbon::create(2025,1,16)],
            ['first_name'=>'GERARDO',        'middle_name'=>'Q.',   'last_name'=>'INSORIO',         'sex'=>'Male',   'contact_number'=>'09181235041', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-041','registration_number'=>'FISHR-2025-041','created_at'=>Carbon::create(2025,1,19)],
            ['first_name'=>'ORLANDO',        'middle_name'=>'V.',   'last_name'=>'FRANCIA',         'sex'=>'Male',   'contact_number'=>'09191235042', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-042','registration_number'=>'FISHR-2025-042','created_at'=>Carbon::create(2025,1,25)],
            ['first_name'=>'RONALD',         'middle_name'=>'A.',   'last_name'=>'VIERNEZA',        'sex'=>'Male',   'contact_number'=>'09171235043', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-043','registration_number'=>'FISHR-2025-043','created_at'=>Carbon::create(2025,1,28)],
            ['first_name'=>'ALVIN',          'middle_name'=>'P.',   'last_name'=>'YABUT',           'sex'=>'Male',   'contact_number'=>'09181235044', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-044','registration_number'=>'FISHR-2025-044','created_at'=>Carbon::create(2025,1,31)],
            ['first_name'=>'WILLIAM',        'middle_name'=>'P.',   'last_name'=>'IÑOSA',           'sex'=>'Male',   'contact_number'=>'09191235045', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-045','registration_number'=>'FISHR-2025-045','created_at'=>Carbon::create(2025,2,3)],
            ['first_name'=>'ELMER',          'middle_name'=>'S.',   'last_name'=>'GAVIOLA',         'sex'=>'Male',   'contact_number'=>'09171235046', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-046','registration_number'=>'FISHR-2025-046','created_at'=>Carbon::create(2025,2,6)],
            ['first_name'=>'ERNIE',          'middle_name'=>'M.',   'last_name'=>'BOLA',            'sex'=>'Male',   'contact_number'=>'09181235047', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-047','registration_number'=>'FISHR-2025-047','created_at'=>Carbon::create(2025,2,9)],
            ['first_name'=>'ROBERTO',        'middle_name'=>'S.',   'last_name'=>'PAULIN',          'sex'=>'Male',   'contact_number'=>'09191235048', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-048','registration_number'=>'FISHR-2025-048','created_at'=>Carbon::create(2025,2,12)],
            ['first_name'=>'ROMAN',          'middle_name'=>'V.',   'last_name'=>'VIBAR',           'sex'=>'Male',   'contact_number'=>'09171235049', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-049','registration_number'=>'FISHR-2025-049','created_at'=>Carbon::create(2025,2,15)],
            ['first_name'=>'RENATO',         'middle_name'=>'D.',   'last_name'=>'DELA CRUZ',       'sex'=>'Male',   'contact_number'=>'09181235050', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-050','registration_number'=>'FISHR-2025-050','created_at'=>Carbon::create(2025,2,18)],
            ['first_name'=>'ROBERTO',        'middle_name'=>'R.',   'last_name'=>'NOTA',            'sex'=>'Male',   'contact_number'=>'09191235051', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-051','registration_number'=>'FISHR-2025-051','created_at'=>Carbon::create(2025,2,27)],
            ['first_name'=>'NESTOR',         'middle_name'=>'C.',   'last_name'=>'DORADO',          'sex'=>'Male',   'contact_number'=>'09171235052', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-052','registration_number'=>'FISHR-2025-052','created_at'=>Carbon::create(2025,1,5)],
            ['first_name'=>'CHRISTOPHER',    'middle_name'=>'B.',   'last_name'=>'AVELINA',         'sex'=>'Male',   'contact_number'=>'09181235053', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-053','registration_number'=>'FISHR-2025-053','created_at'=>Carbon::create(2025,1,8)],
            ['first_name'=>'BLANQUITO',      'middle_name'=>'R.',   'last_name'=>'SARIO',           'sex'=>'Male',   'contact_number'=>'09191235054', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-054','registration_number'=>'FISHR-2025-054','created_at'=>Carbon::create(2025,1,11)],
            ['first_name'=>'SAMUEL',         'middle_name'=>'W.',   'last_name'=>'RAMOS',           'sex'=>'Male',   'contact_number'=>'09171235055', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-055','registration_number'=>'FISHR-2025-055','created_at'=>Carbon::create(2025,2,10)],
            ['first_name'=>'BUSHRA',         'middle_name'=>'A.',   'last_name'=>'JACARIA',         'sex'=>'Female', 'contact_number'=>'09181235056', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-056','registration_number'=>'FISHR-2025-056','created_at'=>Carbon::create(2025,2,13)],
            ['first_name'=>'NURDIN',         'middle_name'=>'T.',   'last_name'=>'TOTOH',           'sex'=>'Male',   'contact_number'=>'09191235057', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-057','registration_number'=>'FISHR-2025-057','created_at'=>Carbon::create(2025,3,1)],
            ['first_name'=>'BHIJAY',         'middle_name'=>'N.',   'last_name'=>'CASINOS',         'sex'=>'Male',   'contact_number'=>'09171235058', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-058','registration_number'=>'FISHR-2025-058','created_at'=>Carbon::create(2025,3,6)],
            ['first_name'=>'EMMANUEL',       'middle_name'=>'C.',   'last_name'=>'GONZALES',        'sex'=>'Male',   'contact_number'=>'09181235059', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-059','registration_number'=>'FISHR-2025-059','created_at'=>Carbon::create(2025,3,11)],
            ['first_name'=>'ATANACIO',       'middle_name'=>'B.',   'last_name'=>'INSORIO',         'sex'=>'Male',   'contact_number'=>'09191235060', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-060','registration_number'=>'FISHR-2025-060','created_at'=>Carbon::create(2025,3,16)],
            ['first_name'=>'SHELVIE ANN',    'middle_name'=>'R.',   'last_name'=>'VILLADIEGO',      'sex'=>'Female', 'contact_number'=>'09171235061', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-061','registration_number'=>'FISHR-2025-061','created_at'=>Carbon::create(2025,3,26)],
            ['first_name'=>'ELBRANDO',       'middle_name'=>'M.',   'last_name'=>'CURAMPES',        'sex'=>'Male',   'contact_number'=>'09181235062', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-062','registration_number'=>'FISHR-2025-062','created_at'=>Carbon::create(2025,4,1)],
            ['first_name'=>'AMILO',          'middle_name'=>'G.',   'last_name'=>'TEMPROSA',        'sex'=>'Male',   'contact_number'=>'09191235063', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-063','registration_number'=>'FISHR-2025-063','created_at'=>Carbon::create(2025,4,6)],
            ['first_name'=>'JEREMIE',        'middle_name'=>'T.',   'last_name'=>'LETH',            'sex'=>'Male',   'contact_number'=>'09171235064', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-064','registration_number'=>'FISHR-2025-064','created_at'=>Carbon::create(2025,4,11)],
            ['first_name'=>'CALIX',          'middle_name'=>'A.',   'last_name'=>'ESPARAGOZA',      'sex'=>'Male',   'contact_number'=>'09181235065', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-065','registration_number'=>'FISHR-2025-065','created_at'=>Carbon::create(2025,4,16)],
            ['first_name'=>'ARTUR',          'middle_name'=>'S.',   'last_name'=>'DELA CRUZ',       'sex'=>'Male',   'contact_number'=>'09191235066', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-066','registration_number'=>'FISHR-2025-066','created_at'=>Carbon::create(2025,4,26)],
            ['first_name'=>'NORMAN',         'middle_name'=>'V.',   'last_name'=>'DITABLAN',        'sex'=>'Male',   'contact_number'=>'09171235067', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-067','registration_number'=>'FISHR-2025-067','created_at'=>Carbon::create(2025,5,1)],
            ['first_name'=>'MARK ANGELO',    'middle_name'=>'R.',   'last_name'=>'DOROTEO',         'sex'=>'Male',   'contact_number'=>'09181235068', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2025-068','registration_number'=>'FISHR-2025-068','created_at'=>Carbon::create(2025,5,6)],

            // ==================== 2026 DATA ====================
            ['first_name'=>'JELLA',          'middle_name'=>'MONTEMAYORES',  'last_name'=>'BACHECHA',        'sex'=>'Female', 'contact_number'=>'09191236001', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2026-001','registration_number'=>'FISHR-2026-001','created_at'=>Carbon::create(2026,1,5)],
            ['first_name'=>'ELEANOR',        'middle_name'=>'BECONIA',       'last_name'=>'BALUYOT',         'sex'=>'Female', 'contact_number'=>'09171236002', 'barangay'=>'Landayan', 'main_livelihood'=>'vending',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2026-002','registration_number'=>'FISHR-2026-002','created_at'=>Carbon::create(2026,1,12)],
            ['first_name'=>'RENATO',         'middle_name'=>'RODRIGUEZ',     'last_name'=>'CRISTOSTOMO',     'sex'=>'Male',   'contact_number'=>'09181236003', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2026-003','registration_number'=>'FISHR-2026-003','created_at'=>Carbon::create(2026,1,20)],
            ['first_name'=>'REYNALDO',       'middle_name'=>'CASPE',         'last_name'=>'LIM',             'sex'=>'Male',   'contact_number'=>'09191236004', 'barangay'=>'Cuyab',    'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2026-004','registration_number'=>'FISHR-2026-004','created_at'=>Carbon::create(2026,2,1)],
            ['first_name'=>'JERNIE',         'middle_name'=>'CALINOG',       'last_name'=>'TOLDANES',        'sex'=>'Male',   'contact_number'=>'09171236005', 'barangay'=>'Landayan', 'main_livelihood'=>'capture',    'secondary_livelihood'=>null, 'fishr_number'=>'FISHR-2026-005','registration_number'=>'FISHR-2026-005','created_at'=>Carbon::create(2026,2,10)],

            // ==================== 2026 BOAT OWNERS (continuing from 006) ====================
            ['first_name'=>'RODRIGO',        'middle_name'=>'R.',   'last_name'=>'RAGUIT',          'sex'=>'Male',   'contact_number'=>'09181236006', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-006','registration_number'=>'FISHR-2026-006','created_at'=>Carbon::create(2026,1,5)],
            ['first_name'=>'EDGARDO',        'middle_name'=>'V.',   'last_name'=>'CORDOVA',         'sex'=>'Male',   'contact_number'=>'09191236007', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-007','registration_number'=>'FISHR-2026-007','created_at'=>Carbon::create(2026,1,10)],
            ['first_name'=>'TOTENG',         'middle_name'=>'A.',   'last_name'=>'SALAZAR',         'sex'=>'Male',   'contact_number'=>'09171236008', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-008','registration_number'=>'FISHR-2026-008','created_at'=>Carbon::create(2026,1,15)],
            ['first_name'=>'FORTE',          'middle_name'=>'M.',   'last_name'=>'OLIVAREZ',        'sex'=>'Male',   'contact_number'=>'09181236009', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-009','registration_number'=>'FISHR-2026-009','created_at'=>Carbon::create(2026,1,20)],
            ['first_name'=>'ZALDY',          'middle_name'=>'P.',   'last_name'=>'FLAMIANO',        'sex'=>'Male',   'contact_number'=>'09191236010', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-010','registration_number'=>'FISHR-2026-010','created_at'=>Carbon::create(2026,1,25)],
            ['first_name'=>'LEONARDO',       'middle_name'=>'V.',   'last_name'=>'VERZOSA',         'sex'=>'Male',   'contact_number'=>'09171236011', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-011','registration_number'=>'FISHR-2026-011','created_at'=>Carbon::create(2026,1,30)],
            ['first_name'=>'RONALD',         'middle_name'=>'A.',   'last_name'=>'LIM',             'sex'=>'Male',   'contact_number'=>'09181236012', 'barangay'=>'Landayan', 'main_livelihood'=>'capture','secondary_livelihood'=>null,'fishr_number'=>'FISHR-2026-012','registration_number'=>'FISHR-2026-012','created_at'=>Carbon::create(2026,2,5)],
        ];

        $createdCount = 0;
        $updatedCount = 0;

        foreach ($fisherfolkData as $data) {
            $recordData = [
                'first_name'                 => $this->toProperCase($data['first_name']),
                'middle_name'                => $this->toProperCase($data['middle_name']),
                'last_name'                  => $this->toProperCase($data['last_name']),
                'name_extension'             => null,
                'sex'                        => $data['sex'],
                'barangay'                   => $data['barangay'],
                'contact_number'             => $data['contact_number'],
                'main_livelihood'            => $data['main_livelihood'],
                'secondary_livelihood'       => $data['secondary_livelihood'] ?? null,
                'other_secondary_livelihood' => $data['other_secondary_livelihood'] ?? null,
                'status'                     => 'approved',
                'status_updated_at'          => $data['created_at'],
                'updated_by'                 => 1,
                'registration_number'        => $data['registration_number'],
                'fishr_number_assigned_at'   => $data['created_at'],
                'fishr_number_assigned_by'   => 1,
                'updated_at'                 => $data['created_at'],
            ];

            $existing = FishrApplication::where('fishr_number', $data['fishr_number'])->first();
            if ($existing) {
                $existing->update($recordData);
                $updatedCount++;
            } else {
                $recordData['fishr_number'] = $data['fishr_number'];
                $recordData['created_at']   = $data['created_at'];
                FishrApplication::create($recordData);
                $createdCount++;
            }
        }

        $this->command->info('FisherfolkRegisteredSeeder executed successfully!');
        $this->command->info("Records created  : {$createdCount}");
        $this->command->info("Records updated  : {$updatedCount}");
        $this->command->info('Total records in database: ' . FishrApplication::count());
    }

    private function toProperCase(?string $value): ?string
    {
        return $value ? ucwords(strtolower($value)) : null;
    }
}