<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Inventory;
use Carbon\Carbon;

class FormBasedInventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $adminUserId = 1; // Assuming admin user ID is 1

        $inventoryItems = [
            // Vegetable Seedlings
            [
                'item_name' => 'Sampaguita',
                'category' => 'vegetables',
                'variety' => null,
                'description' => 'Sampaguita vegetable seedlings',
                'current_stock' => 150,
                'minimum_stock' => 20,
                'maximum_stock' => 500,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(5),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Siling Haba',
                'category' => 'vegetables',
                'variety' => 'Long Chili',
                'description' => 'Long green chili pepper seedlings',
                'current_stock' => 120,
                'minimum_stock' => 25,
                'maximum_stock' => 400,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(3),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Siling Labuyo',
                'category' => 'vegetables',
                'variety' => 'Hot Chili',
                'description' => 'Small hot chili pepper seedlings',
                'current_stock' => 80,
                'minimum_stock' => 15,
                'maximum_stock' => 300,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(7),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Eggplant',
                'category' => 'vegetables',
                'variety' => 'Purple Eggplant',
                'description' => 'Purple eggplant seedlings',
                'current_stock' => 95,
                'minimum_stock' => 20,
                'maximum_stock' => 350,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(4),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Kamatis',
                'category' => 'vegetables',
                'variety' => 'Tomato',
                'description' => 'Tomato seedlings',
                'current_stock' => 200,
                'minimum_stock' => 30,
                'maximum_stock' => 600,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(2),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Okra',
                'category' => 'vegetables',
                'variety' => 'Lady\'s Finger',
                'description' => 'Okra vegetable seedlings',
                'current_stock' => 75,
                'minimum_stock' => 15,
                'maximum_stock' => 250,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(6),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Kalabasa',
                'category' => 'vegetables',
                'variety' => 'Squash',
                'description' => 'Squash seedlings',
                'current_stock' => 60,
                'minimum_stock' => 10,
                'maximum_stock' => 200,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(8),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Upo',
                'category' => 'vegetables',
                'variety' => 'Bottle Gourd',
                'description' => 'Bottle gourd seedlings',
                'current_stock' => 45,
                'minimum_stock' => 10,
                'maximum_stock' => 150,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(9),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Pipino',
                'category' => 'vegetables',
                'variety' => 'Cucumber',
                'description' => 'Cucumber seedlings',
                'current_stock' => 85,
                'minimum_stock' => 15,
                'maximum_stock' => 300,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(5),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],

            // Fruit-bearing Seedlings
            [
                'item_name' => 'Kalamansi',
                'category' => 'fruits',
                'variety' => 'Citrus',
                'description' => 'Kalamansi fruit tree seedlings',
                'current_stock' => 40,
                'minimum_stock' => 8,
                'maximum_stock' => 120,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(10),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Guyabano',
                'category' => 'fruits',
                'variety' => 'Soursop',
                'description' => 'Guyabano fruit tree seedlings',
                'current_stock' => 25,
                'minimum_stock' => 5,
                'maximum_stock' => 80,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(12),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Lanzones',
                'category' => 'fruits',
                'variety' => 'Lansium',
                'description' => 'Lanzones fruit tree seedlings',
                'current_stock' => 30,
                'minimum_stock' => 5,
                'maximum_stock' => 100,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(15),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Mangga',
                'category' => 'fruits',
                'variety' => 'Mango',
                'description' => 'Mango fruit tree seedlings',
                'current_stock' => 35,
                'minimum_stock' => 5,
                'maximum_stock' => 100,
                'unit' => 'pieces',
                'last_restocked' => $now->subDays(20),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],

            // Organic Fertilizers
            [
                'item_name' => 'Pre-processed Chicken Manure',
                'category' => 'fertilizers',
                'variety' => 'Organic Fertilizer',
                'description' => 'Processed chicken manure for organic farming',
                'current_stock' => 50,
                'minimum_stock' => 10,
                'maximum_stock' => 200,
                'unit' => 'sacks',
                'last_restocked' => $now->subDays(7),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Humic Acid',
                'category' => 'fertilizers',
                'variety' => 'Soil Conditioner',
                'description' => 'Humic acid for soil conditioning and plant growth',
                'current_stock' => 30,
                'minimum_stock' => 8,
                'maximum_stock' => 100,
                'unit' => 'bottles',
                'last_restocked' => $now->subDays(14),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
            [
                'item_name' => 'Vermicast',
                'category' => 'fertilizers',
                'variety' => 'Worm Castings',
                'description' => 'Organic vermicast fertilizer from earthworms',
                'current_stock' => 75,
                'minimum_stock' => 15,
                'maximum_stock' => 250,
                'unit' => 'sacks',
                'last_restocked' => $now->subDays(5),
                'created_by' => $adminUserId,
                'updated_by' => $adminUserId,
                'is_active' => true,
            ],
        ];

        foreach ($inventoryItems as $item) {
            Inventory::create($item);
        }

        $this->command->info('Form-based inventory items with sample stocks seeded successfully!');
    }
}
