<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\UserRegistration;
use Carbon\Carbon;

class UserRegistrationSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $users = [
            // ──────────────────────────────────────────────────
            // APPROVED — Fully verified users with complete profiles
            // ──────────────────────────────────────────────────
            [
                'username'          => 'mario_espaldon',
                'contact_number'    => '09176428153',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Mario',
                'middle_name'       => 'Estrellado',
                'last_name'         => 'Espaldon',
                'sex'               => 'Male',
                'date_of_birth'     => '1978-05-14',
                'age'               => 47,
                'user_type'         => 'farmer',
                'barangay'          => 'Calendola',
                'complete_address'  => 'Blk 3 Lot 12, Calendola, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Elena Espaldon',
                'emergency_contact_phone' => '09285431076',
                'approved_at'       => Carbon::create(2025, 2, 10),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'gloria_apilan',
                'contact_number'    => '09289531407',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Gloria',
                'middle_name'       => 'Marquez',
                'last_name'         => 'Apilan',
                'sex'               => 'Female',
                'date_of_birth'     => '1985-11-22',
                'age'               => 40,
                'user_type'         => 'fisherfolk',
                'barangay'          => 'Cuyab',
                'complete_address'  => 'Sitio Riverside, Cuyab, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Roberto Apilan',
                'emergency_contact_phone' => '09173820641',
                'approved_at'       => Carbon::create(2025, 3, 5),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'luisito_casilag',
                'contact_number'    => '09193720856',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Luisito',
                'middle_name'       => 'Orpel',
                'last_name'         => 'Casilag',
                'sex'               => 'Male',
                'date_of_birth'     => '1972-08-03',
                'age'               => 53,
                'user_type'         => 'fisherfolk',
                'barangay'          => 'Landayan',
                'complete_address'  => '123 Fisherman St., Landayan, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Rosalinda Casilag',
                'emergency_contact_phone' => '09362045187',
                'approved_at'       => Carbon::create(2025, 4, 18),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'merlinda_borja',
                'contact_number'    => '09154283691',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Merlinda',
                'middle_name'       => 'Padilla',
                'last_name'         => 'Borja',
                'sex'               => 'Female',
                'date_of_birth'     => '1980-01-29',
                'age'               => 46,
                'user_type'         => 'general',
                'barangay'          => 'Landayan',
                'complete_address'  => 'Phase 2 Blk 7, Landayan, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Roberto Borja',
                'emergency_contact_phone' => '09178342560',
                'approved_at'       => Carbon::create(2025, 5, 2),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'bernadette_morcilla',
                'contact_number'    => '09512436878',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Bernadette',
                'middle_name'       => null,
                'last_name'         => 'Morcilla',
                'sex'               => 'Female',
                'date_of_birth'     => '1990-06-15',
                'age'               => 35,
                'user_type'         => 'farmer',
                'barangay'          => 'Landayan',
                'complete_address'  => '45 Sampaguita St., Landayan, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Jose Morcilla',
                'emergency_contact_phone' => '09204573182',
                'approved_at'       => Carbon::create(2025, 7, 20),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'teodoro_clemente',
                'contact_number'    => '09261834507',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Teodoro',
                'middle_name'       => null,
                'last_name'         => 'Clemente',
                'sex'               => 'Male',
                'date_of_birth'     => '1965-04-10',
                'age'               => 60,
                'user_type'         => 'fisherfolk',
                'barangay'          => 'Cuyab',
                'complete_address'  => 'Purok 2, Cuyab, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Maria Clemente',
                'emergency_contact_phone' => '09175032841',
                'approved_at'       => Carbon::create(2025, 8, 12),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'cherry_cordova',
                'contact_number'    => '09224178817',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Cherry',
                'middle_name'       => null,
                'last_name'         => 'Cordova',
                'sex'               => 'Female',
                'date_of_birth'     => '1988-07-19',
                'age'               => 37,
                'user_type'         => 'farmer',
                'barangay'          => 'San Vicente',
                'complete_address'  => 'Blk 10 Lot 5, San Vicente, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Robert Cordova',
                'emergency_contact_phone' => '09381042756',
                'approved_at'       => Carbon::create(2025, 9, 3),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'aurora_esmasin',
                'contact_number'    => '09100494683',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Aurora',
                'middle_name'       => 'Garcia',
                'last_name'         => 'Esmasin',
                'sex'               => 'Female',
                'date_of_birth'     => '1970-12-25',
                'age'               => 55,
                'user_type'         => 'farmer',
                'barangay'          => 'Magsaysay',
                'complete_address'  => '78 Rizal Ave., Magsaysay, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Pedro Esmasin',
                'emergency_contact_phone' => '09457120386',
                'approved_at'       => Carbon::create(2025, 10, 15),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'romeo_anda',
                'contact_number'    => '09667683989',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Romeo',
                'middle_name'       => 'Delos Santos',
                'last_name'         => 'Anda',
                'sex'               => 'Male',
                'date_of_birth'     => '1983-02-14',
                'age'               => 43,
                'user_type'         => 'general',
                'barangay'          => 'Nueva',
                'complete_address'  => 'Purok 6, Nueva, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Lina Anda',
                'emergency_contact_phone' => '09273061845',
                'approved_at'       => Carbon::create(2025, 11, 8),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'concepcion_staana',
                'contact_number'    => '09302226742',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Concepcion',
                'middle_name'       => null,
                'last_name'         => 'Sta. Ana',
                'sex'               => 'Female',
                'date_of_birth'     => '1976-09-30',
                'age'               => 49,
                'user_type'         => 'farmer',
                'barangay'          => 'San Antonio',
                'complete_address'  => 'Blk 8 Lot 20, San Antonio, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Manuel Sta. Ana',
                'emergency_contact_phone' => '09194057231',
                'approved_at'       => Carbon::create(2025, 12, 1),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'virginia_sabocor',
                'contact_number'    => '09157241949',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Virginia',
                'middle_name'       => null,
                'last_name'         => 'Sabocor',
                'sex'               => 'Female',
                'date_of_birth'     => '1974-03-08',
                'age'               => 52,
                'user_type'         => 'farmer',
                'barangay'          => 'San Antonio',
                'complete_address'  => '12 Mabini St., San Antonio, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Ricardo Sabocor',
                'emergency_contact_phone' => '09358042173',
                'approved_at'       => Carbon::create(2026, 1, 14),
                'approved_by'       => 1,
            ],
            [
                'username'          => 'lina_delrosario',
                'contact_number'    => '09173022213',
                'password'          => 'password123',
                'status'            => 'approved',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Lina',
                'middle_name'       => null,
                'last_name'         => 'Del Rosario',
                'sex'               => 'Female',
                'date_of_birth'     => '1969-10-17',
                'age'               => 56,
                'user_type'         => 'general',
                'barangay'          => 'Maharlika',
                'complete_address'  => 'Phase 1, Maharlika, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Napoleon Del Rosario',
                'emergency_contact_phone' => '09942497516',
                'approved_at'       => Carbon::create(2026, 2, 5),
                'approved_by'       => 1,
            ],

            // ──────────────────────────────────────────────────
            // PENDING — Submitted verification, awaiting admin review
            // ──────────────────────────────────────────────────
            [
                'username'          => 'alfonso_temproza',
                'contact_number'    => '09362158704',
                'password'          => 'password123',
                'status'            => 'pending',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Alfonso',
                'middle_name'       => 'Abundo',
                'last_name'         => 'Temproza',
                'sex'               => 'Male',
                'date_of_birth'     => '1968-03-21',
                'age'               => 58,
                'user_type'         => 'fisherfolk',
                'barangay'          => 'Cuyab',
                'complete_address'  => 'Purok 4, Cuyab, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Sofia Temproza',
                'emergency_contact_phone' => '09208743962',
            ],
            [
                'username'          => 'marivic_catalan',
                'contact_number'    => '09702716168',
                'password'          => 'password123',
                'status'            => 'pending',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Marivic',
                'middle_name'       => 'Gonzales',
                'last_name'         => 'Catalan',
                'sex'               => 'Female',
                'date_of_birth'     => '1992-09-08',
                'age'               => 33,
                'user_type'         => 'farmer',
                'barangay'          => 'San Roque',
                'complete_address'  => 'Blk 15 Lot 8, San Roque, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Roberto Catalan',
                'emergency_contact_phone' => '09183025741',
            ],
            [
                'username'          => 'raul_santos',
                'contact_number'    => '09151801135',
                'password'          => 'password123',
                'status'            => 'pending',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Raul',
                'middle_name'       => 'Navidad',
                'last_name'         => 'Santos',
                'sex'               => 'Male',
                'date_of_birth'     => '1975-12-25',
                'age'               => 50,
                'user_type'         => 'farmer',
                'barangay'          => 'Pacita 1',
                'complete_address'  => 'Phase 3 Blk 2, Pacita 1, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Lina Santos',
                'emergency_contact_phone' => '09276140832',
            ],
            [
                'username'          => 'rizal_castro',
                'contact_number'    => '09166239872',
                'password'          => 'password123',
                'status'            => 'pending',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Rizal',
                'middle_name'       => null,
                'last_name'         => 'Castro',
                'sex'               => 'Male',
                'date_of_birth'     => '1987-06-12',
                'age'               => 38,
                'user_type'         => 'farmer',
                'barangay'          => 'Magsaysay',
                'complete_address'  => 'Purok 3, Magsaysay, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Rachel Castro',
                'emergency_contact_phone' => '09338676618',
            ],
            [
                'username'          => 'esther_villareal',
                'contact_number'    => '09760017762',
                'password'          => 'password123',
                'status'            => 'pending',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
                'first_name'        => 'Esther',
                'middle_name'       => 'Berroya',
                'last_name'         => 'Villareal',
                'sex'               => 'Female',
                'date_of_birth'     => '1981-11-03',
                'age'               => 44,
                'user_type'         => 'general',
                'barangay'          => 'Maharlika',
                'complete_address'  => 'Phase 4 Blk 11, Maharlika, City of San Pedro, Laguna',
                'emergency_contact_name'  => 'Rjoefe Villareal',
                'emergency_contact_phone' => '09765380664',
            ],

            // ──────────────────────────────────────────────────
            // UNVERIFIED — Just registered, haven't submitted verification yet
            // ──────────────────────────────────────────────────
            [
                'username'          => 'nurmin_totoh',
                'contact_number'    => '09935812647',
                'password'          => 'password123',
                'status'            => 'unverified',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
            ],
            [
                'username'          => 'susan_aguilar',
                'contact_number'    => '09517293048',
                'password'          => 'password123',
                'status'            => 'unverified',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
            ],
            [
                'username'          => 'ramil_justo',
                'contact_number'    => '09224567890',
                'password'          => 'password123',
                'status'            => 'unverified',
                'terms_accepted'    => true,
                'privacy_accepted'  => true,
            ],
        ];

        foreach ($users as $user) {
            // Add random working-hour time to approved_at
            if (isset($user['approved_at']) && $user['approved_at'] instanceof Carbon) {
                $user['approved_at'] = $user['approved_at']->copy()->setTime(rand(8, 16), rand(0, 59), rand(0, 59));
                // created_at is a few days before approval (realistic processing window)
                $user['created_at'] = $user['approved_at']->copy()->subDays(rand(2, 7))
                    ->setTime(rand(8, 16), rand(0, 59), rand(0, 59));
            } elseif ($user['status'] === 'pending') {
                // Pending users registered recently
                $user['created_at'] = Carbon::create(2026, 3, rand(10, 25))
                    ->setTime(rand(8, 16), rand(0, 59), rand(0, 59));
            } else {
                // Unverified users just registered in the last few days
                $user['created_at'] = Carbon::create(2026, 3, rand(25, 30))
                    ->setTime(rand(8, 16), rand(0, 59), rand(0, 59));
            }
            UserRegistration::create($user);
        }

        $this->command->info('20 users seeded (12 approved, 5 pending, 3 unverified).');
    }
}