{{-- resources/views/admin/activity-logs/compliance-report.blade.php --}}

@extends('layouts.app')

@section('title', 'Compliance Report - AgriSys Admin')
@section('page-title')
    <div class="d-flex align-items-center gap-3">
        <div class="d-flex align-items-center">
            <i class="fas fa-certificate text-success me-2"></i>
            <span class="text-success fw-bold">ISO 27001 Compliance Report</span>
        </div>
        <a href="{{ route('admin.activity-logs.index') }}" class="btn btn-sm btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Logs
        </a>
    </div>
@endsection

@section('content')
<div class="container-fluid">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="mb-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.activity-logs.index') }}">Activity Logs</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Compliance Report</li>
        </ol>
    </nav>

    <!-- Report Header -->
    <div class="card mb-4 bg-light">
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <h3>ISO 27001 Activity Logging & Monitoring Compliance</h3>
                    <p class="text-muted mb-0">
                        <strong>Generated:</strong> {{ $report['generated_at']->format('M d, Y \a\t h:i A') }}
                    </p>
                    <p class="text-muted">
                        <strong>Generated By:</strong> {{ $report['generated_by'] }}
                    </p>
                </div>
                <div class="col-md-4 text-end">
                    <div style="font-size: 3rem; color: #28a745; opacity: 0.3;">
                        <i class="fas fa-shield-alt"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Compliance Status Overview -->
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-success text-white">
                    <h5 class="mb-0"><i class="fas fa-check-circle"></i> Compliance Status</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0">
                                    <div class="badge bg-success" style="font-size: 1rem; padding: 0.5rem 1rem;">
                                        <i class="fas fa-check"></i>
                                    </div>
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h6>Control A.8.15 - Access Control</h6>
                                    <p class="text-muted small mb-0">
                                        ✓ Activity logging enabled<br>
                                        ✓ Audit trail maintained<br>
                                        ✓ User actions tracked with IP & user agent
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-3">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0">
                                    <div class="badge bg-success" style="font-size: 1rem; padding: 0.5rem 1rem;">
                                        <i class="fas fa-check"></i>
                                    </div>
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h6>Control A.8.16 - Logging & Monitoring</h6>
                                    <p class="text-muted small mb-0">
                                        ✓ Superadmin-only access<br>
                                        ✓ View tracking implemented<br>
                                        ✓ Suspicious activity alerts enabled
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-3">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0">
                                    <div class="badge bg-success" style="font-size: 1rem; padding: 0.5rem 1rem;">
                                        <i class="fas fa-check"></i>
                                    </div>
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h6>Control A.12.4.1 - Event Logging</h6>
                                    <p class="text-muted small mb-0">
                                        ✓ Security events captured<br>
                                        ✓ Failed login tracking<br>
                                        ✓ Privilege change logging
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-3">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0">
                                    <div class="badge bg-success" style="font-size: 1rem; padding: 0.5rem 1rem;">
                                        <i class="fas fa-check"></i>
                                    </div>
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h6>Control A.12.4.2 - Log Protection</h6>
                                    <p class="text-muted small mb-0">
                                        ✓ {{ $report['retention_policy'] }} retention<br>
                                        ✓ Archive system implemented<br>
                                        ✓ Access restricted to {{ $report['access_restricted_to'] }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Policy & Requirements -->
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0"><i class="fas fa-file-alt"></i> Retention Policy</h5>
                </div>
                <div class="card-body">
                    <table class="table table-sm">
                        <tr>
                            <td><strong>Minimum Retention:</strong></td>
                            <td>{{ $report['retention_policy'] }}</td>
                        </tr>
                        <tr>
                            <td><strong>Storage Method:</strong></td>
                            <td>Database + Archive</td>
                        </tr>
                        <tr>
                            <td><strong>Archive Location:</strong></td>
                            <td>Secure local storage</td>
                        </tr>
                        <tr>
                            <td><strong>Automatic Cleanup:</strong></td>
                            <td>Scheduled daily</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0"><i class="fas fa-lock"></i> Access Control</h5>
                </div>
                <div class="card-body">
                    <table class="table table-sm">
                        <tr>
                            <td><strong>View Logs:</strong></td>
                            <td><span class="badge bg-danger">{{ $report['access_restricted_to'] }}</span></td>
                        </tr>
                        <tr>
                            <td><strong>Export Logs:</strong></td>
                            <td><span class="badge bg-danger">{{ $report['access_restricted_to'] }}</span></td>
                        </tr>
                        <tr>
                            <td><strong>Delete Logs:</strong></td>
                            <td><span class="badge bg-danger">{{ $report['access_restricted_to'] }}</span></td>
                        </tr>
                        <tr>
                            <td><strong>Archive Logs:</strong></td>
                            <td><span class="badge bg-danger">{{ $report['access_restricted_to'] }}</span></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Log Integrity -->
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-warning text-dark">
                    <h5 class="mb-0"><i class="fas fa-fingerprint"></i> Log Integrity & Protection</h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="table-light">
                                <tr>
                                    <th>Protection Measure</th>
                                    <th>Status</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><strong>SHA-256 Signatures</strong></td>
                                    <td><span class="badge bg-success">Enabled</span></td>
                                    <td>All log records include integrity signatures to detect tampering</td>
                                </tr>
                                <tr>
                                    <td><strong>IP & User Agent Tracking</strong></td>
                                    <td><span class="badge bg-success">Enabled</span></td>
                                    <td>Every activity includes source IP and device information</td>
                                </tr>
                                <tr>
                                    <td><strong>Read-Only Archive</strong></td>
                                    <td><span class="badge bg-success">Enabled</span></td>
                                    <td>Archived logs cannot be modified after creation</td>
                                </tr>
                                <tr>
                                    <td><strong>View Tracking</strong></td>
                                    <td><span class="badge bg-success">Enabled</span></td>
                                    <td>All log views are recorded for audit purposes</td>
                                </tr>
                                <tr>
                                    <td><strong>Automatic Alerts</strong></td>
                                    <td><span class="badge bg-success">Enabled</span></td>
                                    <td>Suspicious activities trigger immediate notifications</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Events Tracked -->
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <h5 class="mb-0"><i class="fas fa-clipboard-list"></i> Events Tracked (ISO A.8.15)</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h6 class="mb-3">Authentication & Access Events</h6>
                            <ul class="list-unstyled">
                                <li><i class="fas fa-check-circle text-success me-2"></i> User logins (successful)</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Failed login attempts</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> User logouts</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Password reset requests</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Role/permission changes</li>
                            </ul>
                        </div>

                        <div class="col-md-6">
                            <h6 class="mb-3">Data & System Events</h6>
                            <ul class="list-unstyled">
                                <li><i class="fas fa-check-circle text-success me-2"></i> Data creation/modification</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Data deletion</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Log exports</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> Configuration changes</li>
                                <li><i class="fas fa-check-circle text-success me-2"></i> System errors/exceptions</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Exports -->
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <h5 class="mb-0"><i class="fas fa-download"></i> Recent Log Exports (Audit Trail)</h5>
                </div>
                <div class="card-body">
                    @if($report['recent_exports']->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th>Date/Time</th>
                                        <th>Exported By</th>
                                        <th>Records</th>
                                        <th>Date Range</th>
                                        <th>IP Address</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($report['recent_exports'] as $export)
                                        <tr>
                                            <td>{{ $export->created_at->format('M d, Y H:i') }}</td>
                                            <td>
                                                {{ $export->causer->name ?? 'System' }}
                                            </td>
                                            <td>
                                                <span class="badge bg-info">
                                                    {{ $export->properties['exported_count'] ?? 0 }}
                                                </span>
                                            </td>
                                            <td class="small">
                                                {{ $export->properties['date_range']['from'] ?? 'N/A' }} to 
                                                {{ $export->properties['date_range']['to'] ?? 'N/A' }}
                                            </td>
                                            <td>
                                                <code class="small">{{ $export->properties['ip_address'] ?? 'N/A' }}</code>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <p class="text-muted text-center my-4">No recent exports</p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Statistics -->
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h5 class="mb-0"><i class="fas fa-database"></i> Database Statistics</h5>
                </div>
                <div class="card-body">
                    <table class="table table-sm">
                        <tr>
                            <td><strong>Total Log Records:</strong></td>
                            <td><strong class="text-primary">{{ $report['total_logs'] }}</strong></td>
                        </tr>
                        <tr>
                            <td><strong>Database Size:</strong></td>
                            <td>Auto-managed</td>
                        </tr>
                        <tr>
                            <td><strong>Oldest Record:</strong></td>
                            <td>Within retention policy</td>
                        </tr>
                        <tr>
                            <td><strong>Last Cleanup:</strong></td>
                            <td>Daily automated</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h5 class="mb-0"><i class="fas fa-info-circle"></i> Compliance Statement</h5>
                </div>
                <div class="card-body">
                    <p class="small">
                        <strong>Declaration:</strong> This organization has implemented activity logging and 
                        monitoring controls in accordance with ISO/IEC 27001:2022 standards, specifically:
                    </p>
                    <ul class="small">
                        <li>Control A.8.15 - Logging</li>
                        <li>Control A.8.16 - Monitoring activities</li>
                        <li>Control A.12.4.1 - Event logging</li>
                        <li>Control A.12.4.2 - Protection of log information</li>
                    </ul>
                    <p class="small text-muted mt-2">
                        This report is generated for compliance verification and audit purposes only.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="alert alert-primary" role="alert">
        <strong><i class="fas fa-file-pdf"></i> Print/Download:</strong> Use your browser's print function (Ctrl+P or Cmd+P) 
        to save this report as PDF for record-keeping purposes.
    </div>

    <!-- Navigation -->
    <div class="mt-4 mb-4">
        <a href="{{ route('admin.activity-logs.index') }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Activity Logs
        </a>
        <a href="{{ route('admin.activity-logs.audit-summary') }}" class="btn btn-info">
            <i class="fas fa-chart-bar"></i> View Audit Summary
        </a>
    </div>

</div>

<style>
    @media print {
        .btn, button, .alert { display: none !important; }
        body { background: white; }
        .card { page-break-inside: avoid; }
    }
</style>

@endsection